### ISSUE TITLE
Request: Add functionality as custom directives 

### ISSUE THREAD

**Issue by Phunky** [ericmcdaniel/vue-panel#4]
Could be helpful when you wish to apply functionality without additional markup.

**Comment by 3mcd** [comment]
Good idea. Something like this?

``` html
<div v-panel grow="1" shrink="0" ...
```

**Comment by 3mcd** [comment]
#5 - This should cover your request. Let me know if it works for you.

**Comment by Phunky** [comment]
Looks great, sorry for late reply xmas and all :) :+1:
